yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    # Страница сообществ
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    # Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # Создание записи
    path('create/', views.post_create, name='post_create'),
    # Редактирование записи
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    # Добавление комментария к записи
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    # Список постов по подписке
    path('follow/', views.follow_index, name='follow_index'),
    # Подписка на пост
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    # Отписка на пост
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    # Лайк/дизлайк поста
    path(
        'posts/<int:post_id>/like/',
        views.post_like,
        name='post_like'
    ),
    # Дизлайк поста
    path(
        'posts/<int:post_id>/dislike/',
        views.post_dislike,
        name='post_dislike'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(models.Model):
    title = models.CharField(max_length=200,)
    text = models.TextField()
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True,
        db_index=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        'Group',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
    )
    # Поле для картинки (необязательное)
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        'Post',
        on_delete=models.CASCADE,
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField('Текст', help_text='Текст нового комментария')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'], name='unique_author_user_following'
            )
        ]


class Like(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='liker'
    )
    post = models.ForeignKey(
        'Post',
        on_delete=models.CASCADE,
        related_name='liking_post'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'post'], name='unique_post_user_following'
            )
        ]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text', 'group', 'image')
        labels = {'title': 'Заголовок',
                  'text': 'Текст поста',
                  'group': 'Группа',
                  }
        help_texts = {
            'title': 'Название поста',
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относиться пост',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page
from django.http import HttpResponseRedirect

from yatube.settings import PAGE_COUNT

from .forms import CommentForm, PostForm
from .models import Follow, Group, Like, Post, User


def get_page_obj(objects, page_number, items_on_list):
    return Paginator(objects, items_on_list).get_page(page_number)


@cache_page(20)
def index(request):
    post_list = Post.objects.all()
    page_number = request.GET.get('page')
    page_obj = get_page_obj(post_list, page_number, PAGE_COUNT)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    page_number = request.GET.get('page')
    page_obj = get_page_obj(post_list, page_number, PAGE_COUNT)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    # Здесь код запроса к модели и создание словаря контекста
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    post_count = posts.count()
    page_number = request.GET.get('page')
    page_obj = get_page_obj(posts, page_number, PAGE_COUNT)
    following = (
        request.user.is_authenticated
        and Follow.objects.filter(user=request.user,
                                  author=author).exists()
    )
    context = {
        'posts': posts,
        'post_count': post_count,
        'author': author,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    # Здесь код запроса к модели и создание словаря контекста
    post_user = get_object_or_404(Post, pk=post_id)
    post_count = post_user.author.posts.count()
    form = CommentForm(request.POST or None)
    post_comments = post_user.comments.all()
    liking_post_user = (
        request.user.is_authenticated
        and Like.objects.filter(user=request.user, post=post_user).exists()
    )
    count_like_post = Like.objects.filter(post=post_user).count()
    count_post_comments = len(post_comments)
    context = {
        'post_user': post_user,
        'post_count': post_count,
        'form': form,
        'post_comments': post_comments,
        'count_post_comments': count_post_comments,
        'liking_post_user': liking_post_user,
        'count_like_post': count_like_post
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None,
                    files=request.FILES or None
                    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=post.author)
    return render(request, 'posts/create_post.html', {"form": form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:profile', username=post.author)
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post
                    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'form': form,
        'is_edit': True,
        'post': post,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    page_number = request.GET.get('page')
    page_obj = get_page_obj(post_list, page_number, PAGE_COUNT)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author == request.user:
        return redirect('posts:profile', username=username)
    Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    # Дизлайк, отписка
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username=username)


@login_required
def post_like(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    author = post.author
    if author == request.user:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    Like.objects.get_or_create(user=request.user, post=post)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def post_dislike(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    Like.objects.filter(user=request.user, post=post).delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


yatube/templates/posts/includes/comments.html
{% load user_filters %}
{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post_user.pk %}">
        {% csrf_token %}
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}
{% for comment in post_comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
        <p>
         {{ comment.text|linebreaksbr }}
        </p>
        <p>
         {{ comment.created }}
        </p>
      </div>
    </div>
{% endfor %}

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/includes/post_list.html
{% load thumbnail %}
{% load user_filters %}
  <div class="col-xs-6 col-md-6 col-sm-4 mb-4">
    <article>
      <ul>
        <li>
          <i><u>Автор публикации</u>: {{ post.author.get_full_name }}</i>
          <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
        </li>
        <li>
          <i><u>Дата публикации:</u> {{ post.pub_date|date:"d E Y" }}</i>
        </li>
      </ul>
      {% thumbnail post.image "960x339" upscale=True as im %}
        <a class="link-without-decoration" href="{% url 'posts:post_detail' post.pk %}">
          <img class="card-img my-2" src="{{ im.url }}" alt="{{ post.text|truncatewords:5 }}">
        </a>
      {% endthumbnail %}
      <p><h2>{{ post.title }}</h2></p>
      <p>{{ post.text|linebreaksbr |truncatechars:300 }}</p>
      <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
    </article>
      {% if post.group.slug %}
      <a href="{% url 'posts:group_posts' post.group.slug %}">Группа: {{ post.group.title }}
      </a>
      {% endif %}
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <div>
            {% if post|like_filter:user %}
              <a class="badge badge-pill"  href="{% url 'posts:post_dislike' post.pk %}" role="button">
                <b>Нравится</b> <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" fill="#ff4136" class="bi bi-heart" viewBox="0 0 20 20">
                <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/></svg>
              </a>
              {{ post.liking_post.count }}
            {% else %}
              <a class="badge badge-pill"  href="{% url 'posts:post_like' post.pk %}" role="button">
                <b>Нравится</b> <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" fill="#ff4136" class="bi bi-heart" viewBox="0 0 20 20">
                <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/></svg>
              </a>
              {{ post.liking_post.count }}
          {% endif %}

            😍
            <!-- Возвращение прокрутки на исходное место -->
                <script>
                    document.addEventListener("DOMContentLoaded", function (event) {
                        var scrollpos = localStorage.getItem('scrollpos');
                        if (scrollpos) window.scrollTo(0, scrollpos);
                    });
                    window.onbeforeunload = function (e) {
                        localStorage.setItem('scrollpos', window.scrollY);
                    };
                </script>
            <a class="badge badge-pill badge-light" href="{% url 'posts:add_comment' post.pk %}" role="button">
             <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#0074d9" class="bi bi-chat-left" viewBox="0 0 16 16">
                <path d="M14 1a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H4.414A2 2 0 0 0 3 11.586l-2 2V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12.793a.5.5 0 0 0 .854.353l2.853-2.853A1 1 0 0 1 4.414 12H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
              </svg>
            </a>
            <span>{{ post.comments.count }}</span>
        </div>
      </div>
    </div>
    {% if not forloop.last %}<hr>{% endif %}
  </div>

yatube/templates/posts/includes/switcher.html
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a
          class="nav-link {% if index %}active{% endif %}"
          href="{% url 'posts:index' %}"
        >
          <b>Все авторы</b>
        </a>
      </li>
      <li class="nav-item">
        <a
           class="nav-link {% if follow %}active{% endif %}"
           href="{% url 'posts:follow_index' %}"
        >
          <b>Избранные авторы</b>
        </a>
      </li>
    </ul>
  </div>
{% endif %}