yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    # Страница сообществ
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    # Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # Создание записи
    path('create/', views.post_create, name='post_create'),
    # Редактирование записи
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    # Добавление комментария к записи
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    # Список постов по подписке
    path('follow/', views.follow_index, name='follow_index'),
    # Подписка на пост
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    # Отписка на пост
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    # Лайк/дизлайк поста
    path(
        'posts/<int:post_id>/like/',
        views.post_like,
        name='post_like'
    ),
    # Дизлайк поста
    path(
        'posts/<int:post_id>/dislike/',
        views.post_dislike,
        name='post_dislike'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(models.Model):
    title = models.CharField(max_length=200,)
    text = models.TextField()
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True,
        db_index=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        'Group',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
    )
    # Поле для картинки (необязательное)
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        'Post',
        on_delete=models.CASCADE,
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField('Текст', help_text='Текст нового комментария')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'], name='unique_author_user_following'
            )
        ]


class Like(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='liker'
    )
    post = models.ForeignKey(
        'Post',
        on_delete=models.CASCADE,
        related_name='liking_post'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'post'], name='unique_post_user_following'
            )
        ]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text', 'group', 'image')
        labels = {'title': 'Заголовок',
                  'text': 'Текст поста',
                  'group': 'Группа',
                  }
        help_texts = {
            'title': 'Название поста',
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относиться пост',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page
from django.http import HttpResponseRedirect

from yatube.settings import PAGE_COUNT

from .forms import CommentForm, PostForm
from .models import Follow, Group, Like, Post, User


def get_page_obj(objects, page_number, items_on_list):
    return Paginator(objects, items_on_list).get_page(page_number)


@cache_page(20)
def index(request):
    post_list = Post.objects.all()
    page_number = request.GET.get('page')
    page_obj = get_page_obj(post_list, page_number, PAGE_COUNT)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    page_number = request.GET.get('page')
    page_obj = get_page_obj(post_list, page_number, PAGE_COUNT)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    # Здесь код запроса к модели и создание словаря контекста
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    post_count = posts.count()
    page_number = request.GET.get('page')
    page_obj = get_page_obj(posts, page_number, PAGE_COUNT)
    following = (
        request.user.is_authenticated
        and Follow.objects.filter(user=request.user,
                                  author=author).exists()
    )
    context = {
        'posts': posts,
        'post_count': post_count,
        'author': author,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    # Здесь код запроса к модели и создание словаря контекста
    post_user = get_object_or_404(Post, pk=post_id)
    post_count = post_user.author.posts.count()
    form = CommentForm(request.POST or None)
    post_comments = post_user.comments.all()
    liking_post_user = (
        request.user.is_authenticated
        and Like.objects.filter(user=request.user, post=post_user).exists()
    )
    count_like_post = Like.objects.filter(post=post_user).count()
    count_post_comments = len(post_comments)
    context = {
        'post_user': post_user,
        'post_count': post_count,
        'form': form,
        'post_comments': post_comments,
        'count_post_comments': count_post_comments,
        'liking_post_user': liking_post_user,
        'count_like_post': count_like_post
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None,
                    files=request.FILES or None
                    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=post.author)
    return render(request, 'posts/create_post.html', {"form": form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:profile', username=post.author)
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post
                    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'form': form,
        'is_edit': True,
        'post': post,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    page_number = request.GET.get('page')
    page_obj = get_page_obj(post_list, page_number, PAGE_COUNT)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author == request.user:
        return redirect('posts:profile', username=username)
    Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    # Дизлайк, отписка
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username=username)


@login_required
def post_like(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    author = post.author
    if author == request.user:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    Like.objects.get_or_create(user=request.user, post=post)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def post_dislike(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    Like.objects.filter(user=request.user, post=post).delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
{% if is_edit %}
  Редактировать пост
{% else %}
  Новый пост
{% endif %}
{% endblock %}
{% block content %}
{% load user_filters %}
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              {% if is_edit %}
                Редактировать пост
              {% else %}
                Новый пост
              {% endif %}
            </div>
            <div class="card-body">
              <form method="post" enctype="multipart/form-data"
                action="{% if is_edit %} {% url 'posts:post_edit' post.pk %} {% else %} {% url 'posts:post_create' %} {% endif %}">
              {% csrf_token %}
                {% for field in form %}
                <div class="form-group row my-3 p-3">
                  <label for="{{ field.id_for_label }}">
                      {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger" >*</span>
                      {% endif %}
                  </label>
                    {{ field|addclass:"form-control" }}
                    {% if field.help_text %}
                      <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
                {% endfor %}
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    <input type="submit" value="Сохранить">
                  {% else %}
                    <input type="submit" value="Добавить">
                  {% endif %}
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}
  Избранные авторы
{% endblock %}
{% block content %}
  <!-- класс py-5 создает отступы сверху и снизу блока -->
  <div class="container py-5">
    <h1> Мои подписки </h1>
    {% include 'posts/includes/switcher.html' %}
    <div class="row">
      {% for post in page_obj %}
        {% include 'posts/includes/post_list.html' %}
      {% endfor %}
    </div>
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  {{ group.title }}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>
      <b>{{ group.description }}</b>
    </p>
    <div class="row">
    {% for post in page_obj %}
      {% include 'posts/includes/post_list.html' %}
    {% endfor %}
    </div>
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  Последние обновления на сайте
{% endblock %}
{% block content %}
  <!-- класс py-5 создает отступы сверху и снизу блока -->
  <div class="container py-5">
    <h1>Последние обновления на сайте</h1>
    {% include 'posts/includes/switcher.html' %}
    <div class="row">
      {% for post in page_obj %}
        {% include 'posts/includes/post_list.html' %}
      {% endfor %}
    </div>
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
  Пост {{ post_user.title|truncatechars:30 }}
{% endblock %}
{% load thumbnail %}
{% load user_filters %}
{% block content %}
<div class="container py-5">
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <u>Дата публикации:</u> {{ post_user.pub_date|date:"d E Y" }}
          </li>
          {% if post_user.group %}
            <li class="list-group-item">
              <u>Группа:</u> {{ post_user.group.title }}<br>
              <a href="{% url 'posts:group_posts' post_user.group.slug %}">
                все записи группы
              </a>
            </li>
          {% endif %}
          <li class="list-group-item">
            <u>Автор публикации:</u><br>
            {{ post_user.author.get_full_name }} ({{ post_user.author }})
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  <span >{{ post_count }}</span>
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' post_user.author.username %}">
              все посты пользователя
            </a>
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        {% thumbnail post_user.image "960x339" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}" alt="{{ post_user.text|truncatewords:5 }}">
        {% endthumbnail %}
        <p><h2>{{ post_user.title }}</h2></p>
        <p>{{ post_user.text|linebreaksbr }}</p>
        {% if user == post_user.author %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post_user.pk %}">
          редактировать запись
        </a>
        {% endif %}
{#        <div class="article-footer">#}
{#          <span title="Поставить лайк">#}
{#            <a class="link-secondary" href="{% url 'posts:post_like' post_user.pk %}"><i class="far fa-heart"></i>{{ count_like_post }}</a>#}
{#          </span>#}
{#        </div>#}
{#        <footer>#}
{#          <ul class="actions">#}
{#            <li style="display: inline-flex;"></li>#}
{#          </ul>#}
{#          <ul class="stats">#}
{#          <li>#}
{#            <a class="icon solid fa-heart" href="{% url 'posts:post_like' post_user.pk %}"> {{ count_like_post }} </a>#}
{#          </li>#}
{#          </ul>#}
{#        </footer>#}
        <div class="d-flex justify-content-between align-items-center">
          <div class="btn-group">
            <div>
              {% if liking_post_user %}
                <a class="badge badge-pill"  href="{% url 'posts:post_dislike' post_user.pk %}" role="button">
                    <b>Нравится</b> <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" fill="#ff4136" class="bi bi-heart" viewBox="0 0 20 20">
                    <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/></svg>
                </a>
                {{ count_like_post }}
              {% else %}
                <a class="badge badge-pill"  href="{% url 'posts:post_like' post_user.pk %}" role="button">
                    <b>Нравится</b> <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" fill="#ff4136" class="bi bi-heart" viewBox="0 0 20 20">
                    <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/></svg>
                </a>
                {{ count_like_post }}
              {% endif %}
                😍
                <!-- Возвращение прокрутки на исходное место -->
                    <script>
                        document.addEventListener("DOMContentLoaded", function (event) {
                            var scrollpos = localStorage.getItem('scrollpos');
                            if (scrollpos) window.scrollTo(0, scrollpos);
                        });
                        window.onbeforeunload = function (e) {
                            localStorage.setItem('scrollpos', window.scrollY);
                        };
                    </script>
                <a class="badge badge-pill badge-light" href="{% url 'posts:add_comment' post_user.pk %}" role="button">
                 <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#0074d9" class="bi bi-chat-left" viewBox="0 0 16 16">
                    <path d="M14 1a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H4.414A2 2 0 0 0 3 11.586l-2 2V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12.793a.5.5 0 0 0 .854.353l2.853-2.853A1 1 0 0 1 4.414 12H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                  </svg>
                </a>
                <span>{{ count_post_comments }}</span>
            </div>
          </div>
        </div>
        {% include 'posts/includes/comments.html' %}
      </article>
    </div>
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
  {{ author.get_full_name }} профайл пользователя
{% endblock %}
{% load thumbnail %}
{% block content %}
{% load user_filters %}
  <div class="container py-5">
  <div class="mb-5">
    <h1>Все посты пользователя {{ author.get_full_name }}</h1>
    <h3>Всего постов: {{ post_count }}</h3>
    {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author.username %}" role="button"
      >
        Отписаться
      </a>
    {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>
     {% endif %}
  </div>
  <div class="row">
    {% for post in page_obj %}
      <div class="col-xs-6 col-md-6 col-sm-4 mb-4">
        <article>
          <ul>
            <li>
              <i>Дата публикации: {{ post.pub_date|date:"d E Y" }}</i>
            </li>
          </ul>
          {% thumbnail post.image "960x339" upscale=True as im %}
          <a class="link-without-decoration" href="{% url 'posts:post_detail' post.pk %}">
            <img class="card-img my-2" src="{{ im.url }}" alt="{{ post.text|truncatewords:5 }}">
          </a>
          {% endthumbnail %}
          <p><h2>{{ post.title }}</h2></p>
          <p>{{ post.text|linebreaksbr|truncatechars:300 }}</p>
          <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
        </article>
        {% if post.group.slug %}
        <a href="{% url 'posts:group_posts' post.group.slug %}">Группа: {{ post.group.title }}</a>
        {% endif %}
        <div class="d-flex justify-content-between align-items-center">
          <div class="btn-group">
            <div>
              {% if post|like_filter:user %}
                <a class="badge badge-pill"  href="{% url 'posts:post_dislike' post.pk %}" role="button">
                    <b>Нравится</b> <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" fill="#ff4136" class="bi bi-heart" viewBox="0 0 20 20">
                    <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/></svg>
                </a>
                {{ post.liking_post.count }}
              {% else %}
                <a class="badge badge-pill"  href="{% url 'posts:post_like' post.pk %}" role="button">
                    <b>Нравится</b> <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" fill="#ff4136" class="bi bi-heart" viewBox="0 0 20 20">
                    <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/></svg>
                </a>
                {{ post.liking_post.count }}
              {% endif %}

                😍
                <!-- Возвращение прокрутки на исходное место -->
                    <script>
                        document.addEventListener("DOMContentLoaded", function (event) {
                            var scrollpos = localStorage.getItem('scrollpos');
                            if (scrollpos) window.scrollTo(0, scrollpos);
                        });
                        window.onbeforeunload = function (e) {
                            localStorage.setItem('scrollpos', window.scrollY);
                        };
                    </script>
                <a class="badge badge-pill badge-light" href="{% url 'posts:add_comment' post.pk %}" role="button">
                 <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#0074d9" class="bi bi-chat-left" viewBox="0 0 16 16">
                    <path d="M14 1a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H4.414A2 2 0 0 0 3 11.586l-2 2V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12.793a.5.5 0 0 0 .854.353l2.853-2.853A1 1 0 0 1 4.414 12H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                  </svg>
                </a>
                <span>{{ post.comments.count }}</span>
            </div>
          </div>
        </div>
        {% if not forloop.last %}<hr>{% endif %}
      </div>
    {% endfor %}
    </div>
    {% include 'posts/includes/paginator.html' %}

  </div>
{% endblock %}